#include "PluginProcessor.h"
#include "PluginEditor.h"

// Binary data externs (generated by CMake from assets)
extern const char* BinaryData::D1_Kick_1_wav;
extern const int BinaryData::D1_Kick_1_wavSize;
extern const char* BinaryData::D1_Kick_2_wav;
extern const int BinaryData::D1_Kick_2_wavSize;
extern const char* BinaryData::D1_Kick_3_wav;
extern const int BinaryData::D1_Kick_3_wavSize;
extern const char* BinaryData::D1_Kick_4_wav;
extern const int BinaryData::D1_Kick_4_wavSize;

extern const char* BinaryData::D2_Snare_1_wav;
extern const int BinaryData::D2_Snare_1_wavSize;
extern const char* BinaryData::D2_Snare_2_wav;
extern const int BinaryData::D2_Snare_2_wavSize;
extern const char* BinaryData::D2_Snare_3_wav;
extern const int BinaryData::D2_Snare_3_wavSize;
extern const char* BinaryData::D2_Snare_4_wav;
extern const int BinaryData::D2_Snare_4_wavSize;

extern const char* BinaryData::D3_OHH_1_wav;
extern const int BinaryData::D3_OHH_1_wavSize;
extern const char* BinaryData::D3_OHH_2_wav;
extern const int BinaryData::D3_OHH_2_wavSize;
extern const char* BinaryData::D3_OHH_3_wav;
extern const int BinaryData::D3_OHH_3_wavSize;
extern const char* BinaryData::D3_OHH_4_wav;
extern const int BinaryData::D3_OHH_4_wavSize;

extern const char* BinaryData::D4_CHH_1_wav;
extern const int BinaryData::D4_CHH_1_wavSize;
extern const char* BinaryData::D4_CHH_2_wav;
extern const int BinaryData::D4_CHH_2_wavSize;
extern const char* BinaryData::D4_CHH_3_wav;
extern const int BinaryData::D4_CHH_3_wavSize;
extern const char* BinaryData::D4_CHH_4_wav;
extern const int BinaryData::D4_CHH_4_wavSize;

extern const char* BinaryData::D5_Clap_1_wav;
extern const int BinaryData::D5_Clap_1_wavSize;
extern const char* BinaryData::D5_Clap_2_wav;
extern const int BinaryData::D5_Clap_2_wavSize;
extern const char* BinaryData::D5_Clap_3_wav;
extern const int BinaryData::D5_Clap_3_wavSize;
extern const char* BinaryData::D5_Clap_4_wav;
extern const int BinaryData::D5_Clap_4_wavSize;

extern const char* BinaryData::D6_Bell_1_wav;
extern const int BinaryData::D6_Bell_1_wavSize;
extern const char* BinaryData::D6_Bell_2_wav;
extern const int BinaryData::D6_Bell_2_wavSize;
extern const char* BinaryData::D6_Bell_3_wav;
extern const int BinaryData::D6_Bell_3_wavSize;
extern const char* BinaryData::D6_Bell_4_wav;
extern const int BinaryData::D6_Bell_4_wavSize;

TectonicAudioProcessor::TectonicAudioProcessor()
    : AudioProcessor(BusesProperties()
#if !JucePlugin_IsMidiEffect
#if JucePlugin_IsSynth
                         .withOutput("Output", juce::AudioChannelSet::stereo(), true)
#else
                         .withInput("Input", juce::AudioChannelSet::stereo(), true)
                         .withOutput("Output", juce::AudioChannelSet::stereo(), true)
#endif
#endif
      ),
      apvts(*this, nullptr, "Parameters", createParameterLayout())
{
    formatManager.registerBasicFormats();
    loadDrumSamples();
}

TectonicAudioProcessor::~TectonicAudioProcessor() {}

void TectonicAudioProcessor::loadDrumSamples()
{
    // Helper lambda to load a single sample
    auto loadSample = [this](juce::AudioSampleBuffer& destBuffer,
                             const char* data, int dataSize) {
        if (data == nullptr || dataSize <= 0)
            return;

        auto inputStream = std::make_unique<juce::MemoryInputStream>(data, dataSize, false);
        std::unique_ptr<juce::AudioFormatReader> reader(
            formatManager.createReaderFor(std::move(inputStream)));

        if (reader != nullptr)
        {
            destBuffer.setSize(reader->numChannels, (int)reader->lengthInSamples);
            reader->read(&destBuffer, 0, (int)reader->lengthInSamples, 0, true, true);
        }
    };

    // Load all drum samples
    loadSample(drumChannels[0].samples[0], BinaryData::D1_Kick_1_wav, BinaryData::D1_Kick_1_wavSize);
    loadSample(drumChannels[0].samples[1], BinaryData::D1_Kick_2_wav, BinaryData::D1_Kick_2_wavSize);
    loadSample(drumChannels[0].samples[2], BinaryData::D1_Kick_3_wav, BinaryData::D1_Kick_3_wavSize);
    loadSample(drumChannels[0].samples[3], BinaryData::D1_Kick_4_wav, BinaryData::D1_Kick_4_wavSize);

    loadSample(drumChannels[1].samples[0], BinaryData::D2_Snare_1_wav, BinaryData::D2_Snare_1_wavSize);
    loadSample(drumChannels[1].samples[1], BinaryData::D2_Snare_2_wav, BinaryData::D2_Snare_2_wavSize);
    loadSample(drumChannels[1].samples[2], BinaryData::D2_Snare_3_wav, BinaryData::D2_Snare_3_wavSize);
    loadSample(drumChannels[1].samples[3], BinaryData::D2_Snare_4_wav, BinaryData::D2_Snare_4_wavSize);

    loadSample(drumChannels[2].samples[0], BinaryData::D3_OHH_1_wav, BinaryData::D3_OHH_1_wavSize);
    loadSample(drumChannels[2].samples[1], BinaryData::D3_OHH_2_wav, BinaryData::D3_OHH_2_wavSize);
    loadSample(drumChannels[2].samples[2], BinaryData::D3_OHH_3_wav, BinaryData::D3_OHH_3_wavSize);
    loadSample(drumChannels[2].samples[3], BinaryData::D3_OHH_4_wav, BinaryData::D3_OHH_4_wavSize);

    loadSample(drumChannels[3].samples[0], BinaryData::D4_CHH_1_wav, BinaryData::D4_CHH_1_wavSize);
    loadSample(drumChannels[3].samples[1], BinaryData::D4_CHH_2_wav, BinaryData::D4_CHH_2_wavSize);
    loadSample(drumChannels[3].samples[2], BinaryData::D4_CHH_3_wav, BinaryData::D4_CHH_3_wavSize);
    loadSample(drumChannels[3].samples[3], BinaryData::D4_CHH_4_wav, BinaryData::D4_CHH_4_wavSize);

    loadSample(drumChannels[4].samples[0], BinaryData::D5_Clap_1_wav, BinaryData::D5_Clap_1_wavSize);
    loadSample(drumChannels[4].samples[1], BinaryData::D5_Clap_2_wav, BinaryData::D5_Clap_2_wavSize);
    loadSample(drumChannels[4].samples[2], BinaryData::D5_Clap_3_wav, BinaryData::D5_Clap_3_wavSize);
    loadSample(drumChannels[4].samples[3], BinaryData::D5_Clap_4_wav, BinaryData::D5_Clap_4_wavSize);

    loadSample(drumChannels[5].samples[0], BinaryData::D6_Bell_1_wav, BinaryData::D6_Bell_1_wavSize);
    loadSample(drumChannels[5].samples[1], BinaryData::D6_Bell_2_wav, BinaryData::D6_Bell_2_wavSize);
    loadSample(drumChannels[5].samples[2], BinaryData::D6_Bell_3_wav, BinaryData::D6_Bell_3_wavSize);
    loadSample(drumChannels[5].samples[3], BinaryData::D6_Bell_4_wav, BinaryData::D6_Bell_4_wavSize);
}

juce::AudioProcessorValueTreeState::ParameterLayout TectonicAudioProcessor::createParameterLayout()
{
    std::vector<std::unique_ptr<juce::RangedAudioParameter>> params;

    // 6 drum channels
    for (int i = 1; i <= NUM_DRUMS; ++i)
    {
        juce::String prefix = "drum" + juce::String(i);

        // Sound controls
        params.push_back(std::make_unique<juce::AudioParameterFloat>(
            juce::ParameterID{prefix + "_pitch", 1},
            prefix + " Pitch",
            juce::NormalisableRange<float>(-12.0f, 12.0f),
            0.0f));

        params.push_back(std::make_unique<juce::AudioParameterFloat>(
            juce::ParameterID{prefix + "_decay", 1},
            prefix + " Decay",
            juce::NormalisableRange<float>(0.01f, 2.0f, 0.01f),
            0.5f));

        params.push_back(std::make_unique<juce::AudioParameterFloat>(
            juce::ParameterID{prefix + "_overdrive", 1},
            prefix + " Overdrive",
            juce::NormalisableRange<float>(0.0f, 1.0f),
            0.0f));

        // Pattern controls
        params.push_back(std::make_unique<juce::AudioParameterInt>(
            juce::ParameterID{prefix + "_steps", 1},
            prefix + " Steps",
            1, 16, 16));

        params.push_back(std::make_unique<juce::AudioParameterInt>(
            juce::ParameterID{prefix + "_triggers", 1},
            prefix + " Triggers",
            1, 16, 4));

        params.push_back(std::make_unique<juce::AudioParameterInt>(
            juce::ParameterID{prefix + "_offset", 1},
            prefix + " Offset",
            0, 15, 0));
    }

    return {params.begin(), params.end()};
}

std::vector<bool> TectonicAudioProcessor::generateEuclideanPattern(int steps, int triggers, int offset)
{
    std::vector<bool> pattern(steps, false);

    if (steps <= 0 || triggers <= 0)
        return pattern;

    triggers = juce::jmin(triggers, steps);

    // Euclidean algorithm: distribute triggers evenly across steps
    for (int i = 0; i < steps; ++i)
    {
        if ((i * triggers) % steps < triggers)
            pattern[i] = true;
    }

    // Apply offset (rotation)
    if (offset > 0 && offset < steps)
        std::rotate(pattern.rbegin(), pattern.rbegin() + offset, pattern.rend());

    return pattern;
}

void TectonicAudioProcessor::prepareToPlay(double sampleRate, int samplesPerBlock)
{
    currentSampleRate = (sampleRate > 0.0) ? sampleRate : 44100.0;
    lastTotal16thStep = -1;
}

void TectonicAudioProcessor::releaseResources() {}

void TectonicAudioProcessor::processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midiMessages)
{
    juce::ScopedNoDenormals noDenormals;
    auto totalNumOutputChannels = getTotalNumOutputChannels();
    int numSamples = buffer.getNumSamples();

    buffer.clear();

    double bpm = 120.0;
    double startPpq16th = 0.0;
    double ppq16thPerSample = 0.0;
    bool sequencerActive = false;

    if (auto* playHead = getPlayHead())
    {
        auto posInfo = playHead->getPosition();
        if (posInfo.hasValue() && posInfo->getIsPlaying())
        {
            bpm = posInfo->getBpm().hasValue() ? *(posInfo->getBpm()) : 120.0;
            auto ppqPos = posInfo->getPpqPosition().hasValue() ? *(posInfo->getPpqPosition()) : 0.0;

            double ppqPerSample = (bpm / 60.0) / currentSampleRate;
            ppq16thPerSample = ppqPerSample * 4.0;
            startPpq16th = ppqPos * 4.0;
            sequencerActive = true;
        }
    }

    // Process each sample in the buffer
    for (int sampleIdx = 0; sampleIdx < numSamples; ++sampleIdx)
    {
        float leftOut = 0.0f;
        float rightOut = 0.0f;

        // Check for sequencer step trigger
        if (sequencerActive)
        {
            double currentPpq16th = startPpq16th + (sampleIdx * ppq16thPerSample);
            int currentStep = static_cast<int>(std::floor(currentPpq16th));

            if (currentStep != lastTotal16thStep)
            {
                lastTotal16thStep = currentStep;

                // Trigger drums for this step
                for (int drumIdx = 0; drumIdx < NUM_DRUMS; ++drumIdx)
                {
                    auto& drum = drumChannels[drumIdx];
                    if (drum.isMuted.load())
                        continue;

                    auto* steps = apvts.getRawParameterValue("drum" + juce::String(drumIdx + 1) + "_steps");
                    auto* triggers = apvts.getRawParameterValue("drum" + juce::String(drumIdx + 1) + "_triggers");
                    auto* offset = apvts.getRawParameterValue("drum" + juce::String(drumIdx + 1) + "_offset");

                    int s = static_cast<int>(steps->load());
                    int t = static_cast<int>(triggers->load());
                    int o = static_cast<int>(offset->load());

                    if (s > 0)
                    {
                        auto pattern = generateEuclideanPattern(s, t, o);
                        if (!pattern.empty())
                        {
                            int patIdx = currentStep % s;
                            if (patIdx < 0)
                                patIdx += s;

                            if (pattern[patIdx])
                                drum.trigger();
                        }
                    }
                }
            }
        }

        // Render all active drum voices
        for (int drumIdx = 0; drumIdx < NUM_DRUMS; ++drumIdx)
        {
            auto& drum = drumChannels[drumIdx];
            if (!drum.isPlaying.load())
                continue;

            const auto* sampleBuffer = drum.getActiveBuffer();
            if (sampleBuffer == nullptr || sampleBuffer->getNumSamples() == 0)
                continue;

            auto* pitchParam = apvts.getRawParameterValue("drum" + juce::String(drumIdx + 1) + "_pitch");
            auto* decayParam = apvts.getRawParameterValue("drum" + juce::String(drumIdx + 1) + "_decay");
            auto* driveParam = apvts.getRawParameterValue("drum" + juce::String(drumIdx + 1) + "_overdrive");

            float pitch = pitchParam->load();
            float decay = decayParam->load();
            float overdrive = driveParam->load();

            // Calculate playback speed from pitch
            double speedRatio = std::pow(2.0, pitch / 12.0);

            // Calculate decay coefficient
            double decayTimeSamples = decay * currentSampleRate;
            float decayCoeff = (decayTimeSamples > 0.0) ? std::exp(-1.0f / static_cast<float>(decayTimeSamples)) : 0.0f;

            // Read current sample
            double readPtr = drum.readPointer.load();
            int idx = static_cast<int>(readPtr);
            float frac = static_cast<float>(readPtr - idx);

            int numFrames = sampleBuffer->getNumSamples();
            if (idx >= numFrames - 1)
            {
                drum.isPlaying.store(false);
                drum.readPointer.store(0.0);
                drum.envLevel.store(0.0f);
                continue;
            }

            // Linear interpolation between samples
            float s0L = sampleBuffer->getSample(0, idx);
            float s1L = sampleBuffer->getSample(0, idx + 1);
            float left = s0L + frac * (s1L - s0L);

            float right = left;
            if (sampleBuffer->getNumChannels() > 1)
            {
                float s0R = sampleBuffer->getSample(1, idx);
                float s1R = sampleBuffer->getSample(1, idx + 1);
                right = s0R + frac * (s1R - s0R);
            }

            // Apply envelope
            float env = drum.envLevel.load();
            left *= env;
            right *= env;

            // Apply overdrive if active
            if (overdrive > 0.01f)
            {
                float driveGain = 1.0f + (overdrive * 6.0f);
                left *= driveGain;
                right *= driveGain;

                auto softClip = [](float x) {
                    if (x > 1.25f)
                        return 1.0f;
                    if (x < -1.25f)
                        return -1.0f;
                    return x - (x * x * x) * 0.15f;
                };

                left = softClip(left) / std::sqrt(driveGain);
                right = softClip(right) / std::sqrt(driveGain);
            }

            leftOut += left;
            rightOut += right;

            // Update playback position and envelope
            drum.readPointer.store(readPtr + speedRatio);
            env *= decayCoeff;
            drum.envLevel.store(env);

            if (env < 0.0005f)
            {
                drum.isPlaying.store(false);
                drum.envLevel.store(0.0f);
            }
        }

        // Write to output
        if (buffer.getNumChannels() > 0)
            buffer.addSample(0, sampleIdx, leftOut);
        if (buffer.getNumChannels() > 1)
            buffer.addSample(1, sampleIdx, rightOut);
    }
}

bool TectonicAudioProcessor::isBusesLayoutSupported(const BusesLayout& layouts) const
{
    auto mainOut = layouts.getMainOutputChannelSet();
    return mainOut == juce::AudioChannelSet::stereo() || mainOut == juce::AudioChannelSet::mono();
}

const juce::String TectonicAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

void TectonicAudioProcessor::getStateInformation(juce::MemoryBlock& destData)
{
    auto state = apvts.copyState();
    std::unique_ptr<juce::XmlElement> xml(state.createXml());
    if (xml != nullptr)
        copyXmlToBinary(*xml, destData);
}

void TectonicAudioProcessor::setStateInformation(const void* data, int sizeInBytes)
{
    std::unique_ptr<juce::XmlElement> xmlState(getXmlFromBinary(data, sizeInBytes));
    if (xmlState != nullptr && xmlState->hasTagName(apvts.state.getType()))
        apvts.replaceState(juce::ValueTree::fromXml(*xmlState));
}

juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new TectonicAudioProcessor();
}
